version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.0-alpine
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: foodgram-db
    restart: always

  backend:
    build: ../backend/
    env_file: ../.env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    container_name: foodgram-backend
    restart: always

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  gateway:
    container_name: ../gateway/
    ports:
      - "80:80"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always
