# Generated by Django 3.2.3 on 2024-08-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shortlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
