# Generated by Django 3.2.3 on 2024-08-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
