# Generated by Django 3.2.3 on 2024-08-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20240813_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
