# Generated by Django 3.2.3 on 2024-08-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_short_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_code',
        ),
    ]
