# Generated by Django 3.2.3 on 2024-08-16 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Меньше минуты'), django.core.validators.MaxValueValidator(32000, message='Блюдо сгорит')], verbose_name='Время приготовления, мин'),
        ),
    ]
