# Generated by Django 3.2.3 on 2024-08-19 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ничего нет'), django.core.validators.MaxValueValidator(32000, message='Нет места')], verbose_name='Количество'),
        ),
    ]
