# Generated by Django 3.2.3 on 2024-08-17 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240817_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_following_follower',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='users_subscribe_prevent_self_follow',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subscriber',
            field=models.ForeignKey(default=1, help_text='Подписчик автора', on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='author',
            field=models.ForeignKey(help_text='Автор', on_delete=django.db.models.deletion.CASCADE, related_name='subscribing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('subscriber', 'author'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', django.db.models.expressions.F('author')), _negated=True), name='self_follow'),
        ),
    ]
